[package]
name = "argsys"
version = "1.0.2"
edition = "2021"
description = "Simple argument-handler library"
repository = "https://github.com/egevtech/argsys"
license = "GPL-3.0-or-later"

[dependencies]
