[package]
name = "argsys"
version = "0.2.0"
edition = "2024"
description = "Simple argument-handler library"
repository = "https://github.com/egevtech/argsys"
license = "GPL-3.0-or-later"

[dependencies]
